### ISSUE TITLE
Cannot find module 'nodobjc'

### ISSUE THREAD

**Issue by linonetwo** [KELiON/cerebro-osx-define#5]
```

externalPlugins.js:21 Error: Cannot find module 'nodobjc'
Require stack:
- /Applications/Cerebro.app/Contents/Resources/app.asar/main/index.html
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at i._resolveFilename (node:electron/js2c/renderer_init:33:1095)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at i._load (node:electron/js2c/renderer_init:33:356)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/linonetwo/Lib…st/index.js:4071:54)
    at __webpack_require__ (/Users/linonetwo/Lib…dist/index.js:21:30)
    at Object.<anonymous> (/Users/linonetwo/Lib…st/index.js:4054:17)
```

**Comment by linonetwo** [comment]
Sorry, this is caused by  cerebro-case-styles
